#!/bin/bash

numrun=`ps -aux | grep "node /home/pi/urdumbot/index.js" | wc -l`

if [ $numrun -ge 2 ]
then
	echo "Already Running: $numrun"
else
	echo "Starting new process"
	node /home/pi/urdumbot/index.js &
fi
